# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['start_screen.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('icons/acc_icon_1.png', 'icons'),
        ('icons/acc_icon_2.png', 'icons'),
        ('icons/acc_icon_3.png', 'icons'),
        ('icons/acc_icon_4.png', 'icons'),
        ('icons/armchair_icon_1.png', 'icons'),
        ('icons/armchair_icon_2.png', 'icons'),
        ('icons/armchair_icon_3.png', 'icons'),
        ('icons/armchair_icon_4.png', 'icons'),
        ('icons/bed_icon_1.png', 'icons'),
        ('icons/bed_icon_2.png', 'icons'),
        ('icons/bed_icon_3.png', 'icons'),
        ('icons/bed_icon_4.png', 'icons'),
        ('icons/car_section_icon.svg', 'icons'),
        ('icons/casino_icon.webp', 'icons'),
        ('icons/clothing_hoodie_icon.png', 'icons'),
        ('icons/clothing_pants_icon.png', 'icons'),
        ('icons/clothing_section_icon.svg', 'icons'),
        ('icons/clothing_snees_icon.png', 'icons'),
        ('icons/clothing_tshirt_icon.png', 'icons'),
        ('icons/console_icon_1.png', 'icons'),
        ('icons/console_icon_2.png', 'icons'),
        ('icons/console_icon_3.png', 'icons'),
        ('icons/console_icon_4.png', 'icons'),
        ('icons/door_icon.webp', 'icons'),
        ('icons/electronics_accessories_icon.png', 'icons'),
        ('icons/electronics_consoles_icon.png', 'icons'),
        ('icons/electronics_laptops_icon.png', 'icons'),
        ('icons/electronics_section_icon.svg', 'icons'),
        ('icons/electronics_smartphones_icon.png', 'icons'),
        ('icons/furniture_armchairs_icon.png', 'icons'),
        ('icons/furniture_beds_icon.png', 'icons'),
        ('icons/furniture_bookshelves_icon.png', 'icons'),
        ('icons/furniture_section_icon.svg', 'icons'),
        ('icons/furniture_tables_icon.png', 'icons'),
        ('icons/groceries_bread_icon.png', 'icons'),
        ('icons/groceries_fruits_icon.png', 'icons'),
        ('icons/groceries_milk_icon.png', 'icons'),
        ('icons/groceries_section_icon.svg', 'icons'),
        ('icons/groceries_vegetables_icon.png', 'icons'),
        ('icons/gun_revolver_icon.svg', 'icons'),
        ('icons/hatchback_car_icon_1.png', 'icons'),
        ('icons/hatchback_car_icon_2.png', 'icons'),
        ('icons/hatchback_car_icon_3.png', 'icons'),
        ('icons/hatchback_car_icon_4.png', 'icons'),
        ('icons/hatchback_car_icon.png', 'icons'),
        ('icons/home_icon.webp', 'icons'),
        ('icons/laptop_icon_1.png', 'icons'),
        ('icons/laptop_icon_2.png', 'icons'),
        ('icons/laptop_icon_3.png', 'icons'),
        ('icons/laptop_icon_4.png', 'icons'),
        ('icons/pickup_car_icon_1.png', 'icons'),
        ('icons/pickup_car_icon_2.png', 'icons'),
        ('icons/pickup_car_icon_3.png', 'icons'),
        ('icons/pickup_car_icon_4.png', 'icons'),
        ('icons/pickup_car_icon.png', 'icons'),
        ('icons/sedan_car_icon_1.png', 'icons'),
        ('icons/sedan_car_icon_2.png', 'icons'),
        ('icons/sedan_car_icon_3.png', 'icons'),
        ('icons/sedan_car_icon_4.png', 'icons'),
        ('icons/sedan_car_icon.png', 'icons'), 
        ('icons/shelf_icon_1.png', 'icons'),
        ('icons/shelf_icon_2.png', 'icons'),
        ('icons/shelf_icon_3.png', 'icons'),
        ('icons/shelf_icon_4.png', 'icons'),
        ('icons/shopping_center_cars_icon.png', 'icons'),
        ('icons/shopping_center_clothing_icon.png', 'icons'),
        ('icons/shopping_center_electronics_icon.png', 'icons'),
        ('icons/shopping_center_furniture_icon.png', 'icons'),
        ('icons/shopping_center_groceries_icon.png', 'icons'),
        ('icons/shopping_center_tools_icon.png', 'icons'), 
        ('icons/shopping_icon.svg', 'icons'),
        ('icons/smartphone_icon_1.png', 'icons'),
        ('icons/smartphone_icon_2.png', 'icons'),
        ('icons/smartphone_icon_3.png', 'icons'),
        ('icons/smartphone_icon_4.png', 'icons'),
        ('icons/sports_car_icon_1.png', 'icons'),
        ('icons/sports_car_icon_2.png', 'icons'),
        ('icons/sports_car_icon_3.png', 'icons'),
        ('icons/sports_car_icon_4.png', 'icons'),
        ('icons/sports_car_icon.png', 'icons'),
        ('icons/suv_car_icon_1.png', 'icons'),
        ('icons/suv_car_icon_2.png', 'icons'),
        ('icons/suv_car_icon_3.png', 'icons'),
        ('icons/suv_car_icon_4.png', 'icons'),
        ('icons/suv_car_icon.png', 'icons'),
        ('icons/table_icon_1.png', 'icons'),
        ('icons/table_icon_2.png', 'icons'),
        ('icons/table_icon_3.png', 'icons'),
        ('icons/table_icon_4.png', 'icons'),
        ('icons/tools_accessories_icon.png', 'icons'),
        ('icons/tools_hand_tools_icon.png', 'icons'),
        ('icons/tools_power_tools_icon.png', 'icons'),
        ('icons/tools_safety_gear_icon.png', 'icons'),
        ('icons/tools_section_icon.svg', 'icons'),
        ('icons/work_icon.webp', 'icons'),
        ('background_photos/casino_roulette.png', 'background_photos'),
        ('background_photos/city_screen_background.png', 'background_photos'),
        ('background_photos/home_background.png', 'background_photos'),
        ('background_photos/start_screen_background.png', 'background_photos'),
        ('background_photos/game_russian_roulette_background.png', 'background_photos'),
        ('background_photos/work_screen_background.png', 'background_photos'),
        ('background_photos/janitor_screen_background.png', 'background_photos'),
        ('background_photos/dealer_screen_background.png', 'background_photos'),
        ('background_photos/manager_screen_background.png', 'background_photos'),
        ('background_photos/pit_boss_screen_background.png', 'background_photos'), 
        ('background_photos/shift_lead_screen_background.png', 'background_photos'),
        ('background_photos/shift_manager_screen_background.png', 'background_photos'),
        ('background_photos/slot_attendant_screen_background.png', 'background_photos'),
        ('background_photos/waiter_screen_background.png', 'background_photos'),
        ('save_files/information.txt', 'save_files')
    ],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='Gambling_addiction',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
