# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['start_screen.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('icons/car_section_icon.svg', 'icons'),
        ('icons/casino_icon.webp', 'icons'),
        ('icons/door_icon.webp', 'icons'),
        ('icons/gun_revolver_icon.svg', 'icons'),
        ('icons/hatchback_car_icon.png', 'icons'),
        ('icons/home_icon.webp', 'icons'),
        ('icons/pickup_car_icon.png', 'icons'),
        ('icons/sedan_car_icon.png', 'icons'), 
        ('icons/work_icon.webp', 'icons'),
        ('icons/shopping_center_cars_icon.png', 'icons'),
        ('icons/shopping_center_clothing_icon.png', 'icons'),
        ('icons/shopping_center_electronics_icon.png', 'icons'),
        ('icons/shopping_center_furniture_icon.png', 'icons'),
        ('icons/shopping_center_groceries_icon.png', 'icons'),
        ('icons/shopping_center_tools_icon.png', 'icons'), 
        ('icons/shopping_icon.svg', 'icons'),
        ('icons/sports_car_icon.png', 'icons'),
        ('icons/suv_car_icon.png', 'icons'),
        ('background_photos/casino_roulette.png', 'background_photos'),
        ('background_photos/city_screen_background.png', 'background_photos'),
        ('background_photos/home_background.png', 'background_photos'),
        ('background_photos/start_screen_background.png', 'background_photos'),
        ('background_photos/game_russian_roulette_background.png', 'background_photos'),
        ('background_photos/work_screen_background.png', 'background_photos'),
        ('background_photos/janitor_screen_background.png', 'background_photos'),
        ('background_photos/dealer_screen_background.png', 'background_photos'),
        ('background_photos/manager_screen_background.png', 'background_photos'),
        ('background_photos/pit_boss_screen_background.png', 'background_photos'), 
        ('background_photos/shift_lead_screen_background.png', 'background_photos'),
        ('background_photos/shift_manager_screen_background.png', 'background_photos'),
        ('background_photos/slot_attendant_screen_background.png', 'background_photos'),
        ('background_photos/waiter_screen_background.png', 'background_photos'),
        ('save_files/information.txt', 'save_files')
    ],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='Gambling_addiction',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
